### ISSUE TITLE
Unable to control settings

### ISSUE THREAD

**Issue by DavidLeybourne** [binsentsu/home-assistant-solaredge-modbus#295]
With the upgrade to .4 the storage control method changes fail, int has no len.

Reverted back all ok

**Comment by schinzelh** [comment]
Same here

<img width="513" alt="Image" src="https://github.com/user-attachments/assets/a162efcf-4a1c-4112-9ede-cfcd18e73711" />

**Comment by drlkp** [comment]
for me it perform action but after some seconds return to the previous, example not able to disable battery discharge

**Comment by binsentsu** [comment]
should be fixed in V2.0.5. Can you confirm?

**Comment by schinzelh** [comment]
v2.0.5 works for me, thanks!

**Comment by DavidLeybourne** [comment]
Not sure how to upgrade to v2.0.5, but I replaced the init.py with the latest version updated today, and it works again. Plugin still showing v2.0.3 but all seems good.

Thanks for the speedy fix
