### ISSUE TITLE
M1 EXPORTED/IMPORTED KWH resetting to zero periodically

### ISSUE THREAD

**Issue by ministryofsillywalks** [binsentsu/home-assistant-solaredge-modbus#60]
I have an issue where my sensor.solaredge_m1_exported_kwh & sensor.solaredge_m1_imported_kwh are occasionally resetting  "0"
![image](https://user-images.githubusercontent.com/10544895/137459972-fd18b6b5-7dcf-4c3a-a11d-4de064307797.png)
![image](https://user-images.githubusercontent.com/10544895/137461524-2764ff59-e2b2-4f72-9ec2-7c3705b3d8f1.png)

This is somehow happening at pretty similar times:
20:22
06:22
20:15
06:15

It happens to both sensors however not to any other sensors from the modbus integration.
I have no idea whats going on. HA doesn't reboot at these times and also all other network activity seems normal.
These "0" values of course royally screw up my energy dashboard
![image](https://user-images.githubusercontent.com/10544895/137461434-23f94acd-abca-4bcb-b536-77f805bf8f27.png)

Any idea whats going on?

**Comment by mpredfearn** [comment]
@ministryofsillywalks yeah sometimes we get bad data back from the inverter. #44 should fix it once upstream.

**Comment by nerfherder** [comment]
This should now be fixed

**Comment by ChristophCaina** [comment]
Hi, I've just noticed the same behave today - but not periodically...
Is there some way to detect, why the sensor was at zero?

![grafik](https://user-images.githubusercontent.com/26391061/137681304-0f2f02cc-e9e3-4272-a623-24e004562f38.png)
![grafik](https://user-images.githubusercontent.com/26391061/137681314-d46faeec-4446-426c-a834-80049626b682.png)
![grafik](https://user-images.githubusercontent.com/26391061/137681340-93818d67-d18a-4a1d-8128-892cfeb3afc1.png)

**Comment by ChristophCaina** [comment]
ok, I have recalculated the stats in the Database and changed the SUM... for some time, the Dashboard showed the correct data... but then, suddenly, the issue came back, without another "dip" in the sensors log / history...

![grafik](https://user-images.githubusercontent.com/26391061/137687863-0e8767b4-b538-4d2f-abd7-feacad3f6065.png)

Import Sensor
![grafik](https://user-images.githubusercontent.com/26391061/137687880-1fff6278-b84b-4a23-9695-50c5dcbfe65d.png)

Export Sensor
![grafik](https://user-images.githubusercontent.com/26391061/137687901-26a58638-58c7-4e17-adef-ae28e6751280.png)

Stats from 07:00 to 09:30
![grafik](https://user-images.githubusercontent.com/26391061/137687997-cb021c6d-4175-4888-8869-b37eb8a6f21c.png)

the previous dip to 0 [the same than in the comment above]
![grafik](https://user-images.githubusercontent.com/26391061/137688153-7c54bd0d-b059-42c7-b46f-3bb3cc5101e7.png)


How can I fix this in the table - and why did it come back, after recalculating the sum in the DB ?

**Comment by nerfherder** [comment]
What are you editingDB with out of interest?

**Comment by ChristophCaina** [comment]
> So as long as you have the latest version of this integration, any problems observed must be coming from the core.

Currently, I am running Version 1.5.0 of this integration.
I guess, the fix will be in one of the next releases, right?

**Comment by WillCodeForCats** [comment]
Out of curiosity, what's your integration polling interval and how are you connecting to the inverter?

**Comment by TheLordVader** [comment]
Suffering exact same issue starting today, it has never occurred before. Might be core related? Polling interval 5 seconds, working very well before, Ethernet cable and local IP. Messed my energy dashboard completely, did a full restore of backup and deleted Maria dB. Tonight or does to zero again. A half days work and problem is back.
Looking forward to you guys investigating, it is out of my knowledge I'm afraid.
![Screenshot_2021-10-18-20-41-58-072_io homeassistant companion android](https://user-images.githubusercontent.com/23585607/137794309-7a315eef-c7f6-41a9-82b9-04c4d6c0b52b.jpg)

**Comment by gmacioso** [comment]
Just for clarification:

This are not 0 (zeroes), this are nulls (no value) 

So it could be either meter either inverter issue with rs485 communication.
It happened to me while I had 15s, 30s as well as 60s polling.
And, what's more important...

It's for sure not an integration problem, as I run for a year on Domoticz with my own integration. 4 month using Perl script, then switched to Python.
I had same issues there.

So the only thing we can do is to handle this fault by ommiting 0 and null while it comes from SE

**Comment by ChristophCaina** [comment]
Hi @nerfherder, in the past, updating the sum has worked well for me (while I've used the solar edge api integration)... but when I tried it this time - the sum was recalculated with the wrong value on the next statistic calculation.

I am still not sure, if this is related to a change in one of the recent core updates or not... haven't got any further reply or comment on my raised issue on the core repository.

But I've updated this integration now and will observe the issue :)

**Comment by ChristophCaina** [comment]
can be closed
